[package]
name = "qrbill"
version = "0.1.0"
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isocountry = "0.3.2"
textwrap = "0.14.2"
thiserror = "1.0.29"
iban_validate = "4.0.0"
iso_currency = { version = "0.4.1", features = ["with-serde"] }
thousands = "0.2.0"
chrono = "0.4.19"
svg = "0.10.0"
qrcode = "0.12.0"
regex = "1.5.4"

[dev-dependencies]
anyhow = "1.0.44"